ABTester: AB Tester
Caption: Test the experiment
Description: Enter the number of sessions and the number of conversions, and click the "Test" button. You can quantitatively check how much the test pattern is superior to the original.
Original: Original
Pattern: Pattern
SessionCount: Session Count
ConversionCount: Conversion Count
ConversionRate: Conversion Rate
ProbabilityToBeatBaseline: Probability to beat baseline
ProbabilityToBeBest: Probability to be best
Test: Test
